---

- name: Reload systemd
  shell: systemctl daemon-reload

- name: Restart breakerbox
  service: name=breakerbox state=restarted

- name: Restart breakerbox-postgres
  service: name=breakerbox-postgres state=restarted
